### ISSUE TITLE
Bad allocation data

### ISSUE THREAD

**Issue by MLopezPon** [SCIInstitute/ShapeWorks#2358]
Good morning,

I am trying to run an optimization with different domain (ex: vertebra L4-L5).
When running the optimisation step I have a "bad allocation" error stoping the process.
It appears rather when I try with a "bigger cohort" (approx. 100 cases) or more domains (L1 to S1).

To minimize the ressources I first try to run a first groom with the remesh option, take these vertebrea_groomed.vtk as an input of the new model.
This doesn't solve the issue.

Thanks for your help.

![Image](https://github.com/user-attachments/assets/6275e49f-fe93-41bc-8b11-bd7a40959ea1)

**Comment by akenmorris** [comment]
This means that it has run out of memory.  How much RAM does the system have?

You might also try the development version of ShapeWorks where some memory usage has been reduced.

https://github.com/SCIInstitute/ShapeWorks/releases/tag/dev-windows

**Comment by MLopezPon** [comment]
RAM of my present system is 31.6GB.
I'll try the dev version and keep you updated

**Comment by akenmorris** [comment]
There was a very inefficient data structure that scaled poorly with the number of triangles in your groomed meshes.  It's been fixed in the development version, or you can use re-meshing in the groom options to reduce the triangle count.  That could be it.

**Comment by MLopezPon** [comment]
The remeshing groom option was already used in the models that has the "bad allocation" error.
The Development version of the software helps thanks.
I also made a swap for the memory but it is still challenging for the heavier projects (I have some 90GB committed for the full lumbar projects which is still not sufficient).

Last question on this: is a "remesh" option on the grooming phase relevant when the input of the model is an already remeshed groomed? (I took my stls, made a remesh grooming and have the vertebra_groomed.vtk became the input of the new model)

**Comment by akenmorris** [comment]
> Last question on this: is a "remesh" option on the grooming phase relevant when the input of the model is an already remeshed groomed? (I took my stls, made a remesh grooming and have the vertebra_groomed.vtk became the input of the new model)

You can remesh again, if that's what you mean.
