### ISSUE TITLE
Arguments names of python apis do not show when using help(function) 

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#827]
For example, the pad function takes in two argument, no idea what are those arguments are from the help function. Also a brief description for these arguments would be useful.

Can we provide mini examples in the help message?

<img width="989" alt="image" src="https://user-images.githubusercontent.com/3253036/100323435-fce43400-2f82-11eb-9bf6-233483339203.png">

**Comment by sheryjoe** [comment]
@archanasri @cchriste where are we on this issue? please prioritize resolving this issue for the users meeting this week as we discussed in our dev meeting.

**Comment by archanasri** [comment]
pad(...)
    pad(*args, **kwargs)
    Overloaded function.
    
    1. pad(self: shapeworks.Image, pad: int, value: float = 0.0) -> shapeworks.Image
    
    pads an image in all directions with constant value
    
    2. pad(self: shapeworks.Image, padx: int, pady: int, padz: int, value: float = 0.0) -> shapeworks.Image
    
    pads an image by desired number of voxels in each direction with constant value

applyTransform(...)
    applyTransform(*args, **kwargs)
    Overloaded function.
    
    1. applyTransform(self: shapeworks.Image, transform: shapeworks.TransformPtr, interp: shapeworks.InterpolationType = InterpolationType.Linear) -> shapeworks.Image
    
    applies the given transformation to the image by using resampling filter
    
    2. applyTransform(self: shapeworks.Image, transform: shapeworks.TransformPtr, origin: shapeworks.Point, dims: shapeworks.Dims, spacing: shapeworks.Vector, direction: shapeworks.Matrix, interp: shapeworks.InterpolationType = InterpolationType.NearestNeighbor) -> shapeworks.Image
    
    applies the given transformation to the image by using resampling filter with new origin, dims, spacing and direction values

**Comment by archanasri** [comment]
Done with commit 1c8f829

**Comment by sheryjoe** [comment]
@archanasri please checkout the image utils commands.
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/3253036/101564235-02307e00-3988-11eb-9126-53de6d8abc7f.png">

**Comment by archanasri** [comment]
@sheryjoe I noticed it today and just pushed the commit to fix that.

**Comment by sheryjoe** [comment]
@archanasri please check out functions used in the grooming notebook. I recall during the users demo, there was a function that still doesn't have argument names (can't recall which one).

**Comment by archanasri** [comment]
I ran all the notebooks and they all seem to be printing the argument names.

**Comment by archanasri** [comment]
@sheryjoe Can this issue be closed?
